import streamlit as st

LANGUAGES = {
    'zh': {
        'analysis_results': '📊 分析結果',
        'apply_config': '🚀 套用設定',
        'available_models': '📋 可用模型狀態',
        'average_length': '平均長度 (mm)',
        'basic_params': '基本參數',
        'batch_efficiency': '🚀 系統會自動進行批次推理以提高效率',
        'batch_processing': '批次處理',
        'batch_size_info': '📦 批次大小',
        'batches_text': '批次',
        'clear_region': '清除區域',
        'clear_results': '🗑️ 清除結果',
        'color_blue': '藍色',
        'color_green': '綠色',
        'color_red': '紅色',
        'color_white': '白色',
        'color_yellow': '黃色',
        'config_applied': '已套用',
        'config_deleted': '已刪除',
        'config_name': '設定名稱',
        'config_name_help': '為當前的參數配置命名',
        'config_name_placeholder': '輸入新設定的名稱...',
        'config_saved': '已儲存',
        'confidence': '信心度',
        'confidence_threshold': '信心度閾值',
        'confidence_threshold_help': 'YOLO 檢測的信心度閾值',
        'current_model': '🎯 當前模型',
        'delete_config': '🗑️ 刪除設定',
        'display_labels': '顯示長度標籤',
        'display_labels_help': '是否在線條上顯示測量數值',
        'download_complete': '📥 下載完整結果包 (ZIP)',
        'download_complete_help': '包含所有處理後的圖片、Excel 和 CSV 檔案',
        'download_csv': '📋 下載 CSV 檔案',
        'download_csv_help': '下載測量數據的 CSV 格式檔案',
        'download_excel': '📊 下載 Excel 報表',
        'download_excel_help': '下載包含統計分析的 Excel 報表',
        'download_results': '💾 下載結果',
        'enter_config_name': '請輸入設定名稱',
        'failed_images': '❌ 處理失敗的圖片',
        'file_size': '檔案大小',
        'gradient_search_bottom': '往下搜尋距離 (像素)',
        'gradient_search_bottom_help': '向下搜尋血管邊界的最大像素距離',
        'gradient_search_top': '往上搜尋距離 (像素)',
        'gradient_search_top_help': '向上搜尋血管邊界的最大像素距離',
        'image_upload': '📤 圖片上傳',
        'images_text': '張圖片',
        'interactive_selection': '🎨 互動式選擇區域',
        'interactive_selection_help': '在圖片上拖拽滑鼠來選擇矩形區域（只能選擇一個區域）',
        'keep_ratio': '保留寬度比例',
        'keep_ratio_help': '用於邊界調整的寬度保留比例',
        'language_selector': '🌐 語言',
        'line_alpha': '線條透明度',
        'line_alpha_help': '線條的透明度，1為完全不透明',
        'line_color': '線條顏色',
        'line_color_help': '選擇線條的顏色',
        'line_extraction': '🔍 線條提取參數',
        'line_thickness': '線條粗細',
        'line_thickness_help': '繪製線條的粗細程度',
        'main_title': '🔬 血管分割與測量系統',
        'max_average_length': '最大平均長度',
        'mean_length': '平均長度',
        'measurement_data': '📈 測量數據',
        'min_average_length': '最小平均長度',
        'model_failed': '❌ 模型載入失敗',
        'model_file': '模型檔案',
        'model_loaded': '✅ 模型已載入',
        'model_not_loaded': '❌ 模型尚未載入，請先選擇並載入模型',
        'model_selection': '🤖 模型選擇',
        'model_status': '模型狀態',
        'num_lines': '測量線數量',
        'page_icon': '🔬',
        'page_title': '血管分割與測量系統',
        'pixel_size': '像素大小 (mm/pixel)',
        'pixel_size_help': '一個像素對應的實際距離（毫米）',
        'process_all': '🚀 批次處理全部圖片',
        'processing_complete': '處理完成',
        'processing_efficiency': '📊 處理效率',
        'processing_failed': '張圖片處理失敗',
        'range': '範圍',
        'region_limit': '區域限制',
        'region_limit_help': '開啟區域限制，將圖片裁切到選擇的區域進行分析',
        'sample_interval': '採樣間隔 (像素)',
        'sample_interval_help': 'x軸採樣步距，數值越小線條越密集',
        'save_config': '💾 儲存當前設定',
        'save_current_config': '儲存當前設定',
        'select_config': '選擇設定組合',
        'select_config_help': '選擇要套用的設定組合',
        'select_images': '選擇血管圖片',
        'select_images_help': '支援 PNG、JPG、JPEG、BMP、TIFF 格式，建議每批不超過 200 張圖片',
        'select_model': '選擇分析模型',
        'select_model_help': '選擇要使用的血管分割模型',
        'select_video': '選擇影片檔案',
        'settings_management': '💾 設定管理',
        'start_batch_processing': '開始批次處理',
        'std_length': '標準差',
        'success_count': '張成功',
        'successful_processing': '成功處理',
        'switch_model': '🔄 切換模型',
        'system_config': '⚙️ 系統配置',
        'unknown_error': '未知錯誤',
        'uploaded_count': '已上傳',
        'video_upload': '🎥 影片上傳 🚧（功能開發中）',
        'video_upload_help': '支援 MP4、AVI、MOV 格式的影片檔案',
        'video_uploaded': '影片上傳成功',
        'visualization': '🎨 視覺化參數'
    },
    'en': {
        'analysis_results': '📊 Analysis Results',
        'apply_config': '🚀 Apply Configuration',
        'available_models': '📋 Available Models Status',
        'average_length': 'Average Length (mm)',
        'basic_params': 'Basic Parameters',
        'batch_efficiency': '🚀 System automatically performs batch inference for improved efficiency',
        'batch_processing': 'Batch Processing',
        'batch_size_info': '📦 Batch Size',
        'batches_text': 'batches',
        'clear_region': 'Clear Region',
        'clear_results': '🗑️ Clear Results',
        'color_blue': 'Blue',
        'color_green': 'Green',
        'color_red': 'Red',
        'color_white': 'White',
        'color_yellow': 'Yellow',
        'config_applied': 'Configuration applied',
        'config_deleted': 'Configuration deleted',
        'config_name': 'Configuration Name',
        'config_name_help': 'Enter a name for the current parameter configuration',
        'config_name_placeholder': 'Enter new configuration name...',
        'config_saved': 'Configuration saved',
        'confidence': 'Confidence',
        'confidence_threshold': 'Confidence Threshold',
        'confidence_threshold_help': 'Minimum confidence threshold for YOLO detection',
        'current_model': '🎯 Current Model',
        'delete_config': '🗑️ Delete Configuration',
        'display_labels': 'Display Length Labels',
        'display_labels_help': 'Show measurement values on the lines',
        'download_complete': '📥 Download Complete Package (ZIP)',
        'download_complete_help': 'Contains all processed images, Excel and CSV files',
        'download_csv': '📋 Download CSV File',
        'download_csv_help': 'Download measurement data in CSV format',
        'download_excel': '📊 Download Excel Report',
        'download_excel_help': 'Download Excel report with statistical analysis',
        'download_results': '💾 Download Results',
        'enter_config_name': 'Please enter configuration name',
        'failed_images': '❌ Failed Images',
        'file_size': 'File Size',
        'gradient_search_bottom': 'Downward Search Distance (pixels)',
        'gradient_search_bottom_help': 'Maximum pixel distance for downward vessel boundary search',
        'gradient_search_top': 'Upward Search Distance (pixels)',
        'gradient_search_top_help': 'Maximum pixel distance for upward vessel boundary search',
        'image_upload': '📤 Image Upload',
        'images_text': 'images',
        'interactive_selection': '🎨 Interactive Region Selection',
        'interactive_selection_help': 'Drag on the image to select a rectangular region (only one region allowed)',
        'keep_ratio': 'Width Retention Ratio',
        'keep_ratio_help': 'Width retention ratio for boundary adjustment',
        'language_selector': '🌐 Language',
        'line_alpha': 'Line Transparency',
        'line_alpha_help': 'Line transparency level, 1 is completely opaque',
        'line_color': 'Line Color',
        'line_color_help': 'Choose the color for measurement lines',
        'line_extraction': '🔍 Line Extraction Parameters',
        'line_thickness': 'Line Thickness',
        'line_thickness_help': 'Thickness of the drawn measurement lines',
        'main_title': '🔬 Vessel Segmentation & Measurement System',
        'max_average_length': 'Maximum Average Length',
        'mean_length': 'Mean Length',
        'measurement_data': '📈 Measurement Data',
        'min_average_length': 'Minimum Average Length',
        'model_failed': '❌ Model Loading Failed',
        'model_file': 'Model File',
        'model_loaded': '✅ Model Loaded Successfully',
        'model_not_loaded': '❌ No model loaded. Please select and load a model first',
        'model_selection': '🤖 Model Selection',
        'model_status': 'Model Status',
        'num_lines': 'Number of Lines',
        'page_icon': '🔬',
        'page_title': 'Vessel Segmentation & Measurement System',
        'pixel_size': 'Pixel Size (mm/pixel)',
        'pixel_size_help': 'Real-world distance represented by one pixel (in millimeters)',
        'process_all': '🚀 Process All Images',
        'processing_complete': 'Processing completed',
        'processing_efficiency': '📊 Processing Efficiency',
        'processing_failed': 'images failed to process',
        'range': 'Range',
        'region_limit': 'Region Limitation',
        'region_limit_help': 'Enable region limitation to crop and analyze only the selected area',
        'sample_interval': 'Sample Interval (pixels)',
        'sample_interval_help': 'X-axis sampling step size. Smaller values create denser measurement lines',
        'save_config': '💾 Save Current Configuration',
        'save_current_config': 'Save Current Configuration',
        'select_config': 'Select Configuration',
        'select_config_help': 'Choose a configuration preset to apply',
        'select_images': 'Select Vessel Images',
        'select_images_help': 'Supports PNG, JPG, JPEG, BMP, TIFF formats. Recommend max 200 images per batch',
        'select_model': 'Select Analysis Model',
        'select_model_help': 'Choose the vessel segmentation model to use',
        'select_video': 'Select Video File',
        'settings_management': '💾 Settings Management',
        'start_batch_processing': 'Starting batch processing',
        'std_length': 'Standard Deviation',
        'success_count': 'successful',
        'successful_processing': 'Successfully Processed',
        'switch_model': '🔄 Switch Model',
        'system_config': '⚙️ System Configuration',
        'unknown_error': 'Unknown error',
        'uploaded_count': 'Uploaded',
        'video_upload': '🎥 Video Upload 🚧 (Under Development)',
        'video_upload_help': 'Supports MP4, AVI, MOV video file formats',
        'video_uploaded': 'Video uploaded successfully',
        'visualization': '🎨 Visualization Parameters'
    }
}

# Language management functions
def get_text(key):
    """Get text based on current language setting"""
    current_lang = st.session_state.get('language', 'zh')
    return LANGUAGES[current_lang].get(key, key)