import streamlit as st

LANGUAGES = {
    'zh': {
        'page_title': '血管分割與測量系統',
        'page_icon': '🔬',
        'main_title': '🔬 血管分割與測量系統',
        'system_config': '⚙️ 系統配置',
        'model_selection': '🤖 模型選擇',
        'select_model': '選擇分析模型',
        'select_model_help': '選擇要使用的血管分割模型',
        'current_model': '🎯 當前模型',
        'switch_model': '🔄 切換模型',
        'model_file': '模型檔案',
        'model_status': '模型狀態',
        'model_loaded': '✅ 模型已載入',
        'model_failed': '❌ 模型載入失敗',
        'available_models': '📋 可用模型狀態',
        'video_upload': '🎥 影片上傳 🚧（未完成）',
        'settings_management': '💾 設定管理',
        'select_config': '選擇設定組合',
        'select_config_help': '選擇要套用的設定組合',
        'apply_config': '🚀 套用設定',
        'delete_config': '🗑️ 刪除設定',
        'save_current_config': '儲存當前設定',
        'config_name': '設定名稱',
        'config_name_placeholder': '輸入新設定的名稱...',
        'config_name_help': '為當前的參數配置命名',
        'save_config': '💾 儲存當前設定',
        'basic_params': '基本參數',
        'pixel_size': '像素大小 (mm/pixel)',
        'pixel_size_help': '一個像素對應的實際距離',
        'confidence_threshold': '信心度閾值',
        'confidence_threshold_help': 'YOLO 檢測的信心度閾值',
        'line_extraction': '🔍 線條提取參數',
        'sample_interval': '採樣間隔 (像素)',
        'sample_interval_help': 'x軸採樣步距，數值越小線條越密集',
        'gradient_search_top': '往上搜尋距離 (像素)',
        'gradient_search_top_help': '向上搜尋血管邊界的最大像素距離',
        'gradient_search_bottom': '往下搜尋距離 (像素)',
        'gradient_search_bottom_help': '向下搜尋血管邊界的最大像素距離',
        'keep_ratio': '保留寬度比例',
        'keep_ratio_help': '用於邊界調整的寬度保留比例',
        'visualization': '🎨 視覺化參數',
        'line_thickness': '線條粗細',
        'line_thickness_help': '繪製線條的粗細程度',
        'line_alpha': '線條透明度',
        'line_alpha_help': '線條的透明度，1為完全不透明',
        'display_labels': '顯示長度標籤',
        'display_labels_help': '是否顯示長度標籤',
        'line_color': '線條顏色',
        'line_color_help': '選擇線條的顏色',
        'batch_processing': '批次處理',
        'batch_size_info': '📦 批次大小',
        'batch_efficiency': '🚀 系統會自動進行批次推理以提高效率',
        'image_upload': '📤 圖片上傳',
        'select_images': '選擇血管圖片',
        'select_images_help': '建議每批不超過 200 張圖片，單張不可超過 10MB',
        'uploaded_count': '已上傳',
        'process_all': '🚀 批次處理全部圖片',
        'clear_results': '🗑️ 清除結果',
        'analysis_results': '📊 分析結果',
        'successful_processing': '成功處理',
        'average_length': '平均長度 (mm)',
        'max_average_length': '最大平均長度',
        'min_average_length': '最小平均長度',
        'processing_failed': '張圖片處理失敗',
        'measurement_data': '📈 測量數據',
        'confidence': '信心度',
        'num_lines': '測量線數量',
        'mean_length': '平均長度',
        'std_length': '標準差',
        'range': '範圍',
        'failed_images': '❌ 處理失敗的圖片',
        'download_results': '💾 下載結果',
        'download_complete': '📥 下載完整結果包 (ZIP)',
        'download_excel': '📊 下載 Excel 報表',
        'download_csv': '📋 下載 CSV 檔案',
        'processing_efficiency': '📊 處理效率',
        'success_count': '張成功',
        'language_selector': '🌐 語言',
        'color_green': '綠色',
        'color_red': '紅色',
        'color_blue': '藍色',
        'color_white': '白色',
        'color_yellow': '黃色'
    },
    'en': {
        'page_title': 'Vessel Segmentation & Measurement System',
        'page_icon': '🔬',
        'main_title': '🔬 Vessel Segmentation & Measurement System',
        'system_config': '⚙️ System Configuration',
        'model_selection': '🤖 Model Selection',
        'select_model': 'Select Analysis Model',
        'select_model_help': 'Choose the vessel segmentation model to use',
        'current_model': '🎯 Current Model',
        'switch_model': '🔄 Switch Model',
        'model_file': 'Model File',
        'model_status': 'Model Status',
        'model_loaded': '✅ Model Loaded',
        'model_failed': '❌ Model Loading Failed',
        'available_models': '📋 Available Models Status',
        'video_upload': '🎥 Video Upload 🚧 (Not Completed)',
        'settings_management': '💾 Settings Management',
        'select_config': 'Select Configuration',
        'select_config_help': 'Choose configuration to apply',
        'apply_config': '🚀 Apply Settings',
        'delete_config': '🗑️ Delete Settings',
        'save_current_config': 'Save Current Settings',
        'config_name': 'Configuration Name',
        'config_name_placeholder': 'Enter new configuration name...',
        'config_name_help': 'Name for current parameter configuration',
        'save_config': '💾 Save Current Settings',
        'basic_params': 'Basic Parameters',
        'pixel_size': 'Pixel Size (mm/pixel)',
        'pixel_size_help': 'Real distance per pixel',
        'confidence_threshold': 'Confidence Threshold',
        'confidence_threshold_help': 'YOLO detection confidence threshold',
        'line_extraction': '🔍 Line Extraction Parameters',
        'sample_interval': 'Sample Interval (pixels)',
        'sample_interval_help': 'X-axis sampling step, smaller values create denser lines',
        'gradient_search_top': 'Upward Search Distance (pixels)',
        'gradient_search_top_help': 'Maximum pixel distance for upward vessel boundary search',
        'gradient_search_bottom': 'Downward Search Distance (pixels)',
        'gradient_search_bottom_help': 'Maximum pixel distance for downward vessel boundary search',
        'keep_ratio': 'Width Retention Ratio',
        'keep_ratio_help': 'Width retention ratio for boundary adjustment',
        'visualization': '🎨 Visualization Parameters',
        'line_thickness': 'Line Thickness',
        'line_thickness_help': 'Thickness of drawn lines',
        'line_alpha': 'Line Transparency',
        'line_alpha_help': 'Line transparency, 1 is completely opaque',
        'display_labels': 'Display Length Labels',
        'display_labels_help': 'Whether to display length labels',
        'line_color': 'Line Color',
        'line_color_help': 'Select line color',
        'batch_processing': 'Batch Processing',
        'batch_size_info': '📦 Batch Size',
        'batch_efficiency': '🚀 System automatically performs batch inference for efficiency',
        'image_upload': '📤 Image Upload',
        'select_images': 'Select Vessel Images',
        'select_images_help': 'Recommend no more than 200 images per batch, max 10MB per image',
        'uploaded_count': 'Uploaded',
        'process_all': '🚀 Process All Images',
        'clear_results': '🗑️ Clear Results',
        'analysis_results': '📊 Analysis Results',
        'successful_processing': 'Successfully Processed',
        'average_length': 'Average Length (mm)',
        'max_average_length': 'Max Average Length',
        'min_average_length': 'Min Average Length',
        'processing_failed': 'images failed to process',
        'measurement_data': '📈 Measurement Data',
        'confidence': 'Confidence',
        'num_lines': 'Number of Lines',
        'mean_length': 'Mean Length',
        'std_length': 'Standard Deviation',
        'range': 'Range',
        'failed_images': '❌ Failed Images',
        'download_results': '💾 Download Results',
        'download_complete': '📥 Download Complete Results (ZIP)',
        'download_excel': '📊 Download Excel Report',
        'download_csv': '📋 Download CSV File',
        'processing_efficiency': '📊 Processing Efficiency',
        'success_count': 'successful',
        'language_selector': '🌐 Language',
        'color_green': 'Green',
        'color_red': 'Red',
        'color_blue': 'Blue',
        'color_white': 'White',
        'color_yellow': 'Yellow'
    }
}

# 語言管理函數
def get_text(key):
    """根據當前語言獲取文本"""
    current_lang = st.session_state.get('language', 'zh')
    return LANGUAGES[current_lang].get(key, key)