import streamlit as st

LANGUAGES = {
    'zh': {
        'analysis_results': '📊 分析結果',
        'apply_config': '🚀 套用設定',
        'default_config_name': '系統預設',
        'available_models': '📋 可用模型狀態',
        'average_length': '平均長度 (mm)',
        'basic_params': '基本參數',
        'batch_efficiency': '🚀 系統會自動進行批次推理以提高效率',
        'batch_processing': '批次處理',
        'batch_size_info': '📦 批次大小',
        'batches_text': '批次',
        'clear_region': '清除區域',
        'clear_results': '🗑️ 清除結果',
        'color_blue': '藍色',
        'color_green': '綠色',
        'color_red': '紅色',
        'color_white': '白色',
        'color_yellow': '黃色',
        'config_applied': '已套用',
        'config_deleted': '已刪除',
        'config_name': '設定名稱',
        'config_name_help': '為當前的參數配置命名',
        'config_name_placeholder': '輸入新設定的名稱...',
        'config_saved': '已儲存',
        'confidence': '信心度',
        'confidence_threshold': '信心度閾值',
        'confidence_threshold_help': 'YOLO 檢測的信心度閾值',
        'current_model': '🎯 當前模型',
        'delete_config': '🗑️ 刪除設定',
        'display_labels': '顯示長度標籤',
        'display_labels_help': '是否在線條上顯示測量數值',
        'download_complete': '📥 下載完整結果包 (ZIP)',
        'download_complete_help': '包含所有處理後的圖片、Excel 和 CSV 檔案',
        'download_csv': '📋 下載 CSV 檔案',
        'download_csv_help': '下載測量數據的 CSV 格式檔案',
        'download_excel': '📊 下載 Excel 報表',
        'download_excel_help': '下載包含統計分析的 Excel 報表',
        'download_results': '💾 下載結果',
        'download_single_image': '⬇️ 下載該圖片',
        'enter_config_name': '請輸入設定名稱',
        'failed_images': '❌ 處理失敗的圖片',
        'file_size': '檔案大小',
        'gradient_search_bottom': '往下搜尋距離 (像素)',
        'gradient_search_bottom_help': '向下搜尋血管邊界的最大像素距離',
        'gradient_search_top': '往上搜尋距離 (像素)',
        'gradient_search_top_help': '向上搜尋血管邊界的最大像素距離',
        'image_upload': '📤 圖片上傳',
        'images_text': '張圖片',
        'interactive_selection': '🎨 互動式選擇區域',
        'interactive_selection_help': '在圖片上拖拽滑鼠來選擇矩形區域（只能選擇一個區域）',
        'canvas_adjust_selection': '調整選取區域尺寸',
        'canvas_width_label': '寬度 (px)',
        'canvas_height_label': '高度 (px)',
        'canvas_region_status': '目前選擇區域：{region}',
        'canvas_apply_region_button': '套用選區',
        'canvas_selection_saved': '選區已儲存',
        'keep_ratio': '保留寬度比例',
        'keep_ratio_help': '用於邊界調整的寬度保留比例',
        'language_selector': '🌐 語言',
        'line_alpha': '線條透明度',
        'line_alpha_help': '線條的透明度，1為完全不透明',
        'line_color': '線條顏色',
        'line_color_help': '選擇線條的顏色',
        'line_extraction': '🔍 線條提取參數',
        'line_thickness': '線條粗細',
        'line_thickness_help': '繪製線條的粗細程度',
        'main_title': '🔬 血管分割與測量系統',
        'max_average_length': '最大平均長度',
        'mean_length': '平均長度',
        'measurement_data': '📈 測量數據',
        'min_average_length': '最小平均長度',
        'model_failed': '❌ 模型載入失敗',
        'model_file': '模型檔案',
        'model_loaded': '✅ 模型已載入',
        'model_not_loaded': '❌ 模型尚未載入，請先選擇並載入模型',
        'model_selection': '🤖 模型選擇',
        'model_status': '模型狀態',
        'num_lines': '測量線數量',
        'page_icon': '🔬',
        'page_title': '血管分割與測量系統',
        'page_images': '📷 圖片處理',
        'page_videos': '🎞️ 影片處理',
        'page_results': '✅ 結果與下載',
        'nav_label': '🔖 功能',
        'pixel_size': '像素大小 (mm/pixel)',
        'pixel_size_help': '一個像素對應的實際距離（毫米）',
        'process_all': '🚀 批次處理全部圖片',
        'processing_complete': '處理完成',
        'processing_efficiency': '📊 處理效率',
        'processing_failed': '張圖片處理失敗',
        'range': '範圍',
        'region_limit': '區域限制',
        'region_limit_help': '開啟區域限制，將圖片裁切到選擇的區域進行分析',
        'sample_interval': '採樣間隔 (像素)',
        'sample_interval_help': 'x軸採樣步距，數值越小線條越密集',
        'save_config': '💾 儲存當前設定',
        'save_current_config': '儲存當前設定',
        'select_config': '選擇設定組合',
        'select_config_help': '選擇要套用的設定組合',
        'select_images': '選擇血管圖片',
        'select_images_help': '支援 PNG、JPG、JPEG、BMP、TIFF 格式，建議每批不超過 200 張圖片',
        'select_images_upload': '選擇多張圖片',
        'select_model': '選擇分析模型',
        'select_model_help': '選擇要使用的血管分割模型',
        'select_video': '選擇影片檔案',
        'settings_management': '💾 設定管理',
        'start_batch_processing': '開始批次處理',
        'std_length': '標準差',
        'success_count': '張成功',
        'successful_processing': '成功處理',
        'switch_model': '🔄 切換模型',
        'system_config': '⚙️ 系統配置',
        'unknown_error': '未知錯誤',
        'uploaded_count': '已上傳',
        'video_upload': '🎥 影片上傳 🚧（功能開發中）',
        'video_upload_help': '支援 MP4、AVI、MOV 格式的影片檔案',
        'video_uploaded': '影片上傳成功',
        'visualization': '🎨 視覺化參數',
        'config_applied_message': '✅ 設定「{name}」已套用',
        'config_deleted_message': '✅ 設定「{name}」已刪除',
        'config_saved_message': '✅ 設定「{name}」已儲存',
        'delete_failed': '❌ 刪除設定失敗',
        'save_failed': '❌ 儲存設定失敗',
        'cannot_delete_default': '⚠️ 無法刪除預設設定',
        'clear_images': '🗑️ 清空圖片',
        'start_image_batch_processing': '📤 開始批量處理圖片',
        'batch_processing_summary': '共 {count} 張，分 {batches} 批處理',
        'image_processing_complete': '✅ 圖片處理完成',
        'clear_image_results': '🗑️ 清空圖片結果',
        'no_image_results': '尚無圖片處理結果',
        'image_results_title': '📷 圖片處理結果',
        'view_stats': '🔍 查看統計數據',
        'image_processing_failed_count': '⚠️ {count} 張處理失敗',
        'image_success_ratio': '**成功：{success}/{total} 張**',
        'download_zip': '下載 ZIP',
        'max_length': '最大長度',
        'min_length': '最小長度',
        'video_refetch': '重新獲取影片 (假如未出現)',
        'start_video_processing': '📤 開始處理影片',
        'video_interval_required': '請先設定時間區間',
        'video_processing_start': '🔍 開始處理影片 ... 請稍候',
        'video_processing_complete': '✅ 影片處理完成',
        'clear_video_results': '🗑️ 清空影片結果',
        'no_video_results': '尚無影片處理結果',
        'video_results_title': '🎞️ 影片結果檢視',
        'results_tab_images': '📷 圖片結果',
        'results_tab_videos': '🎞️ 影片結果',
        'download_video': '⬇️ 下載影片',
        'frame_count': '幀數',
        'start_time': '開始時間',
        'end_time': '結束時間',
        'max_occurrence_time': '最大出現秒數',
        'video_segment_label': '▶️ 片段',
        'video_intervals_title': '### ⏱️ 設定影片處理區間（秒）',
        'video_intervals_hint': '輸入範例：`75`、`75.5`、`01:15` 或 `0:01:15`',
        'interval_start_label': '開始 (秒 或 hh:mm:ss)',
        'interval_start_placeholder': '例如 75 或 00:01:15',
        'interval_end_label': '結束 (秒 或 hh:mm:ss)',
        'interval_end_placeholder': '例如 100 或 00:01:40',
        'interval_add_button': '➕ 新增區間',
        'interval_end_after_start': '結束時間必須大於開始時間。',
        'interval_added': '已新增：{hms_start} → {hms_end} ({start:.2f}s → {end:.2f}s)',
        'interval_parse_failed': '解析時間失敗：{error}',
        'interval_list_title': '#### 已加入的區間',
        'interval_column_header': '區間 (點選以選取)',
        'interval_column_header_paged': '區間 (第 {page}/{pages} 頁)',
        'intervals_empty': '目前沒有任何區間。請在上方輸入並按「➕ 新增區間」。',
        'interval_multiselect_label': '選取要刪除的區間（可多選）',
        'delete_selected_intervals': '🗑️ 刪除所選',
        'select_intervals_warning': '請先選擇要刪除的區間。',
        'intervals_deleted': '已刪除 {count} 筆。',
        'merge_intervals_button': '🔀 合併重疊區間',
        'intervals_merged': '已合併重疊 / 相接的區間。',
        'clear_intervals': '🧹 清除全部區間',
        'interval_page_label': '頁面',
        'interval_error_invalid_format': '時間格式錯誤 (請使用秒數或 mm:ss 或 hh:mm:ss)',
        'interval_error_invalid_number': '時間段包含非法數字',
        'interval_error_empty': '空字串',
        'google_img_download_subtitle': '🎞️ 從 Google Drive 分享連結下載圖片',
        'google_drive_link_hint_images': '貼上 Google Drive 分享連結 範例 https://drive.google.com/drive/folders/1ppSMdn1YYdc8rN56uKgWJhqezzneajAY?usp=drive_link',
        'google_drive_link_label': 'Drive 分享連結 或 file id',
        'google_img_download_button': '獲取圖片',
        'google_img_info': '請輸入 Google Drive 分享連結然後按獲取圖片 範例 https://drive.google.com/drive/folders/1ppSMdn1YYdc8rN56uKgWJhqezzneajAY?usp=drive_link',
        'google_drive_invalid_link': '請輸入有效的 Google Drive 分享連結或 file id。',
        'google_img_cache_used': '已使用連結緩存 共 {count} 張圖片',
        'google_fetching_data': '獲取資料中...',
        'google_img_download_error': '下載過程發生錯誤：{error}',
        'google_img_download_complete': '下載完成 共 {count} 張圖片',
        'google_img_compressing': '壓縮圖片中...',
        'google_img_compress_complete': '壓縮完成 共 {count} 張圖片',
        'google_video_download_subtitle': '🎞️ 從 Google Drive 分享連結下載影片',
        'google_drive_link_hint_videos': '貼上 Google Drive 分享連結 範例 https://drive.google.com/file/d/1jmK_i5AvezX6fCAZLhTrxm0dUnI3KLQT/view?usp=drive_link',
        'google_video_download_button': '獲取影片',
        'google_video_info': '請輸入 Google Drive 分享連結然後按獲取影片 範例 https://drive.google.com/file/d/1jmK_i5AvezX6fCAZLhTrxm0dUnI3KLQT/view?usp=drive_link',
        'google_video_cached': '已使用連結緩存：{name}',
        'google_video_download_error': '下載過程發生錯誤：{error}',
        'google_video_no_results': '未找到任何關於影片的檔案或下載失敗，請確認連結或權限設定。',
        'google_video_download_complete': '下載完成：{name}',
        'google_video_compressing': '壓縮影片中...',
        'google_video_compress_complete': '壓縮完成：{name}',
        'google_video_fetch_failed': '下載失敗：{error}',
        'google_video_path_missing': '下載失敗：{name} 不存在'
    },
    'en': {
        'analysis_results': '📊 Analysis Results',
        'apply_config': '🚀 Apply Configuration',
        'default_config_name': 'System Default',
        'available_models': '📋 Available Models Status',
        'average_length': 'Average Length (mm)',
        'basic_params': 'Basic Parameters',
        'batch_efficiency': '🚀 System automatically performs batch inference for improved efficiency',
        'batch_processing': 'Batch Processing',
        'batch_size_info': '📦 Batch Size',
        'batches_text': 'batches',
        'clear_region': 'Clear Region',
        'clear_results': '🗑️ Clear Results',
        'color_blue': 'Blue',
        'color_green': 'Green',
        'color_red': 'Red',
        'color_white': 'White',
        'color_yellow': 'Yellow',
        'config_applied': 'Configuration applied',
        'config_deleted': 'Configuration deleted',
        'config_name': 'Configuration Name',
        'config_name_help': 'Enter a name for the current parameter configuration',
        'config_name_placeholder': 'Enter new configuration name...',
        'config_saved': 'Configuration saved',
        'confidence': 'Confidence',
        'confidence_threshold': 'Confidence Threshold',
        'confidence_threshold_help': 'Minimum confidence threshold for YOLO detection',
        'current_model': '🎯 Current Model',
        'delete_config': '🗑️ Delete Configuration',
        'display_labels': 'Display Length Labels',
        'display_labels_help': 'Show measurement values on the lines',
        'download_complete': '📥 Download Complete Package (ZIP)',
        'download_complete_help': 'Contains all processed images, Excel and CSV files',
        'download_csv': '📋 Download CSV File',
        'download_csv_help': 'Download measurement data in CSV format',
        'download_excel': '📊 Download Excel Report',
        'download_excel_help': 'Download Excel report with statistical analysis',
        'download_results': '💾 Download Results',
        'download_single_image': '⬇️ Download image',
        'enter_config_name': 'Please enter configuration name',
        'failed_images': '❌ Failed Images',
        'file_size': 'File Size',
        'gradient_search_bottom': 'Downward Search Distance (pixels)',
        'gradient_search_bottom_help': 'Maximum pixel distance for downward vessel boundary search',
        'gradient_search_top': 'Upward Search Distance (pixels)',
        'gradient_search_top_help': 'Maximum pixel distance for upward vessel boundary search',
        'image_upload': '📤 Image Upload',
        'images_text': 'images',
        'interactive_selection': '🎨 Interactive Region Selection',
        'interactive_selection_help': 'Drag on the image to select a rectangular region (only one region allowed)',
        'keep_ratio': 'Width Retention Ratio',
        'keep_ratio_help': 'Width retention ratio for boundary adjustment',
        'language_selector': '🌐 Language',
        'line_alpha': 'Line Transparency',
        'line_alpha_help': 'Line transparency level, 1 is completely opaque',
        'line_color': 'Line Color',
        'line_color_help': 'Choose the color for measurement lines',
        'line_extraction': '🔍 Line Extraction Parameters',
        'line_thickness': 'Line Thickness',
        'line_thickness_help': 'Thickness of the drawn measurement lines',
        'main_title': '🔬 Vessel Segmentation & Measurement System',
        'max_average_length': 'Maximum Average Length',
        'mean_length': 'Mean Length',
        'measurement_data': '📈 Measurement Data',
        'min_average_length': 'Minimum Average Length',
        'model_failed': '❌ Model Loading Failed',
        'model_file': 'Model File',
        'model_loaded': '✅ Model Loaded Successfully',
        'model_not_loaded': '❌ No model loaded. Please select and load a model first',
        'model_selection': '🤖 Model Selection',
        'model_status': 'Model Status',
        'num_lines': 'Number of Lines',
        'page_icon': '🔬',
        'page_title': 'Vessel Segmentation & Measurement System',
        'page_images': '📷 Image Processing',
        'page_videos': '🎞️ Video Processing',
        'page_results': '✅ Results & Downloads',
        'nav_label': '🔖 Features',
        'pixel_size': 'Pixel Size (mm/pixel)',
        'pixel_size_help': 'Real-world distance represented by one pixel (in millimeters)',
        'process_all': '🚀 Process All Images',
        'processing_complete': 'Processing completed',
        'processing_efficiency': '📊 Processing Efficiency',
        'processing_failed': 'images failed to process',
        'range': 'Range',
        'region_limit': 'Region Limitation',
        'region_limit_help': 'Enable region limitation to crop and analyze only the selected area',
        'sample_interval': 'Sample Interval (pixels)',
        'sample_interval_help': 'X-axis sampling step size. Smaller values create denser measurement lines',
        'save_config': '💾 Save Current Configuration',
        'save_current_config': 'Save Current Configuration',
        'select_config': 'Select Configuration',
        'select_config_help': 'Choose a configuration preset to apply',
        'select_images': 'Select Vessel Images',
        'select_images_help': 'Supports PNG, JPG, JPEG, BMP, TIFF formats. Recommend max 200 images per batch',
        'select_model': 'Select Analysis Model',
        'select_model_help': 'Choose the vessel segmentation model to use',
        'select_video': 'Select Video File',
        'settings_management': '💾 Settings Management',
        'start_batch_processing': 'Starting batch processing',
        'std_length': 'Standard Deviation',
        'success_count': 'successful',
        'successful_processing': 'Successfully Processed',
        'switch_model': '🔄 Switch Model',
        'system_config': '⚙️ System Configuration',
        'unknown_error': 'Unknown error',
        'uploaded_count': 'Uploaded',
        'video_upload': '🎥 Video Upload 🚧 (Under Development)',
        'video_upload_help': 'Supports MP4, AVI, MOV video file formats',
        'video_uploaded': 'Video uploaded successfully',
        'visualization': '🎨 Visualization Parameters',
        'config_applied_message': '✅ Configuration "{name}" applied',
        'config_deleted_message': '✅ Configuration "{name}" deleted',
        'config_saved_message': '✅ Configuration "{name}" saved',
        'delete_failed': '❌ Failed to delete configuration',
        'save_failed': '❌ Failed to save configuration',
        'cannot_delete_default': '⚠️ Cannot delete the default configuration',
        'clear_images': '🗑️ Clear images',
        'start_image_batch_processing': '📤 Start batch image processing',
        'batch_processing_summary': 'Processing {count} images across {batches} batches',
        'image_processing_complete': '✅ Image processing complete',
        'clear_image_results': '🗑️ Clear image results',
        'no_image_results': 'No image results yet',
        'image_results_title': '📷 Image Results',
        'view_stats': '🔍 View statistics',
        'image_processing_failed_count': '⚠️ Failed to process {count} images',
        'image_success_ratio': '**Success: {success}/{total} images**',
        'download_zip': 'Download ZIP',
        'max_length': 'Maximum Length',
        'min_length': 'Minimum Length',
        'video_refetch': 'Refetch video (if it does not appear)',
        'start_video_processing': '📤 Start processing video',
        'video_interval_required': 'Please set time intervals first',
        'video_processing_start': '🔍 Processing video... please wait',
        'video_processing_complete': '✅ Video processing complete',
        'clear_video_results': '🗑️ Clear video results',
        'no_video_results': 'No video results yet',
        'video_results_title': '🎞️ Video results overview',
        'results_tab_images': '📷 Image Results',
        'results_tab_videos': '🎞️ Video Results',
        'download_video': '⬇️ Download video',
        'frame_count': 'Frame Count',
        'start_time': 'Start Time',
        'end_time': 'End Time',
        'max_occurrence_time': 'Max occurrence time (s)',
        'video_segment_label': '▶️ Segment',
        'video_intervals_title': '### ⏱️ Set video processing intervals (seconds)',
        'video_intervals_hint': 'Examples: `75`, `75.5`, `01:15`, or `0:01:15`',
        'interval_start_label': 'Start (seconds or hh:mm:ss)',
        'interval_start_placeholder': 'e.g. 75 or 00:01:15',
        'interval_end_label': 'End (seconds or hh:mm:ss)',
        'interval_end_placeholder': 'e.g. 100 or 00:01:40',
        'interval_add_button': '➕ Add interval',
        'interval_end_after_start': 'End time must be greater than the start time.',
        'interval_added': 'Added: {hms_start} → {hms_end} ({start:.2f}s → {end:.2f}s)',
        'interval_parse_failed': 'Failed to parse time: {error}',
        'interval_list_title': '#### Added intervals',
        'interval_column_header': 'Intervals (click to select)',
        'interval_column_header_paged': 'Intervals (page {page}/{pages})',
        'intervals_empty': 'No intervals yet. Enter values above and click "➕ Add interval".',
        'interval_multiselect_label': 'Select intervals to delete (multi-select)',
        'delete_selected_intervals': '🗑️ Delete selected',
        'select_intervals_warning': 'Please select intervals to delete first.',
        'intervals_deleted': 'Deleted {count} intervals.',
        'merge_intervals_button': '🔀 Merge overlapping intervals',
        'intervals_merged': 'Merged overlapping or adjacent intervals.',
        'clear_intervals': '🧹 Clear all intervals',
        'interval_page_label': 'Page',
        'interval_error_invalid_format': 'Invalid time format (use seconds or mm:ss or hh:mm:ss)',
        'interval_error_invalid_number': 'Interval contains invalid numbers',
        'interval_error_empty': 'Empty string',
        'google_img_download_subtitle': '🎞️ Download images from a Google Drive share link',
        'google_drive_link_hint_images': 'Paste a Google Drive share link, e.g. https://drive.google.com/drive/folders/1ppSMdn1YYdc8rN56uKgWJhqezzneajAY?usp=drive_link',
        'google_drive_link_label': 'Drive share link or file id',
        'google_img_download_button': 'Fetch images',
        'google_img_info': 'Enter a Google Drive share link and click fetch images, e.g. https://drive.google.com/drive/folders/1ppSMdn1YYdc8rN56uKgWJhqezzneajAY?usp=drive_link',
        'google_drive_invalid_link': 'Please enter a valid Google Drive share link or file id.',
        'google_img_cache_used': 'Used cached link: {count} images',
        'google_fetching_data': 'Fetching data...',
        'google_img_download_error': 'Download error occurred: {error}',
        'google_img_download_complete': 'Download complete: {count} images',
        'google_img_compressing': 'Compressing images...',
        'google_img_compress_complete': 'Compression complete: {count} images',
        'google_video_download_subtitle': '🎞️ Download video from a Google Drive share link',
        'google_drive_link_hint_videos': 'Paste a Google Drive share link, e.g. https://drive.google.com/file/d/1jmK_i5AvezX6fCAZLhTrxm0dUnI3KLQT/view?usp=drive_link',
        'google_video_download_button': 'Fetch video',
        'google_video_info': 'Enter a Google Drive share link and click fetch video, e.g. https://drive.google.com/file/d/1jmK_i5AvezX6fCAZLhTrxm0dUnI3KLQT/view?usp=drive_link',
        'google_video_cached': 'Used cached link: {name}',
        'google_video_download_error': 'Download error occurred: {error}',
        'google_video_no_results': 'No video files found or download failed. Check the link or permissions.',
        'google_video_download_complete': 'Download complete: {name}',
        'google_video_compressing': 'Compressing video...',
        'google_video_compress_complete': 'Compression complete: {name}',
        'google_video_fetch_failed': 'Download failed: {error}',
        'google_video_path_missing': 'Download failed: {name} missing',
        'select_images_upload': 'Select multiple images',
        'canvas_adjust_selection': 'Adjust selection area size',
        'canvas_width_label': 'Width (px)',
        'canvas_height_label': 'Height (px)',
        'canvas_region_status': 'Current selection: {region}',
        'canvas_apply_region_button': 'Apply selection',
        'canvas_selection_saved': 'Selection saved'
    }
}

# Language management functions
def get_text(key):
    """Get text based on current language setting"""
    current_lang = st.session_state.get('language', 'zh')
    return LANGUAGES[current_lang].get(key, key)